language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
#- BOARD=uno
- BOARD=nodemcuv2

script:
- set -eo pipefail;
  for e in src/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
